notifications:
  slack: $slack
sudo: required
language: node_js
node_js:
    - "9.7.1"
install:
  - npm i
script:
  - npx ng lint
  - npx ng test @angeeks/gh-layout --watch=false
  - npx ng build @angeeks/gh-layout --prod
  - npx ng test gh-layout --watch=false
  - npx ng build gh-layout --prod --base-href gh-layout
cache:
    directories:
      - node_modules
before_deploy:
  - cp README.md dist/angeeks/gh-layout
  - cd dist/angeeks/gh-layout
deploy:
  - provider: npm
    email: $npmEmail
    api_key: $npm
    skip_cleanup: true
    keep-history: true
    tag: latest
    on:
      branch: release
